// <auto-generated />
namespace EntityFramework.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class School_Adress_Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(School_Adress_Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251549547_School_Adress_Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
