// <auto-generated />
namespace EntityFramework.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_rest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_rest));
        
        string IMigrationMetadata.Id
        {
            get { return "201703311242000_init_rest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
